name: OPPad2
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow

jobs:
  build-kernel-oppad2-kernelsu-susfs:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OPPad2"
      soc: "pineapple"
      branch: "oneplus/sm8650"
      manifest: "oneplus_pad2_v.xml"
      android_version: "android14"
      kernel_version: "6.1"
